-- SQLite
CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50) NOT NULL,
    YEAR INTEGER NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    KM INTEGER NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    BRAND_ID INTEGER,
    MODEL_ID INTEGER,

    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRAND (ID),
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODEL (ID)
)
